## Урок 2
### Матрицы и матричные операции. Часть 1

### Практическое задание. Часть 1

In [28]:
import numpy as np

#### 1. Установите какие произведения матриц A B и B A , определены и найдите размерности полученных матриц:

а) A — матрица 4×2, B — матрица 4×2;  
б) A — матрица 2×5, B — матрица 5×3;  
в) A — матрица 8×3, B — матрица 3×8;  
г) A — квадратная матрица 4 ×4, B — квадратная матрица 4 ×4.

Матрицу A можно умножить на матрицу B, если число столбцов матрицы A было равно числу строк матрицы B.

а) A — матрица 4×2, B — матрица 4×2;  
AB - перемножить нельзя  
BA - перемножить нельзя  

б) A — матрица 2×5, B — матрица 5×3;  
AB - перемножить можно  (2х3)  
BA - перемножить нельзя  

в) A — матрица 8×3, B — матрица 3×8;  
AB - перемножить можно (8х8)  
BA - перемножить можно (3х3)  

г) A — квадратная матрица 4×4, B — квадратная матрица 4×4.   
AB - перемножить можно  (4×4)  
BA - перемножить можно  (4×4)  

#### 2. Найдите сумму и произведение матриц:

A  

    1  -2  
    3   0   
    
В  

    4  -1  
    0   5  

    (1  -2)    +    (4  -1)    =  (5   -3)
    (3   0)         (0   5)       (3    5)

In [29]:
#проверка суммы
a = np.array([[1, -2], [3, 0]])
b = np.array([[4, -1], [0, 5]])
a + b

array([[ 5, -3],
       [ 3,  5]])

    (1  -2)    *    (4  -1)    =  (4   -11)
    (3   0)         (0   5)       (12   -3)

In [30]:
#проверка произведения
a.dot(b)

array([[  4, -11],
       [ 12,  -3]])

#### 3. Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислите линейную комбинацию 3 A −2B+4C

A  

    1   7  
    3  -6   
    
В  

    0   5  
    2  -1
    
C

    2  -4
    1   1

In [31]:
a = np.array([[1, 7], [3, -6]])
b = np.array([[0, 5], [2, -1]])
c = np.array([[2, -4], [1, 1]])
3 * a + (-2) * b + 4 * c

array([[ 11,  -5],
       [  9, -12]])

#### 4.  Дана матрица A
    4   1
    5  -2
    2   3

Вычислите:
$A * A^T \\
A^T *A$

$A^{T} = \begin{pmatrix} 4 & 5 & 2\\ 1 & -2 & 3 \end{pmatrix} $


$A A^{T} = \begin{pmatrix} 4 & 1\\ 5 & -2\\ 2 & 3\end{pmatrix} * \begin{pmatrix} 4 & 5 & 2\\ 1 & -2 & 3 \end{pmatrix} = \begin{pmatrix} 17 & 18 & 11\\ 18 & 29 & 4\\ 11 & 4 & 13\end{pmatrix} $


$A^{T}A = \begin{pmatrix} 4 & 5 & 2\\ 1 & -2 & 3\end{pmatrix} * \begin{pmatrix} 4 & 1\\ 5
& -2\\ 2 & 3 \end{pmatrix} = \begin{pmatrix} 45 & 0\\ 0 & 14 \end{pmatrix} $


In [32]:
A = np.array([[4, 1], [5, -2], [2, 3]])
A.T

array([[ 4,  5,  2],
       [ 1, -2,  3]])

In [33]:
A.dot(A.T)

array([[17, 18, 11],
       [18, 29,  4],
       [11,  4, 13]])

In [34]:
A.T.dot(A)

array([[45,  0],
       [ 0, 14]])

### Практическое задание. Часть 2

#### 1. Вычислить определитель:

a)  
           sinx −cosx  
           cosx sinx
           
$ sin^2x + cos^2x = 1$

б)

    4 2 3
    0 5 1
    0 0 9

$4∗(5∗9−1∗0)−2(0∗9−1∗0)+3 (0∗0−5∗0)=4∗45=180$

в)

    1 2 3
    4 5 6
    7 8 9

$1∗(5∗9−6∗8)−2∗( 4∗9−7∗6)+3∗( 4∗8−5∗7)=0 $

In [35]:
# проверка б)
b = np.array([[4, 2, 3], [0, 5, 1], [0, 0, 9]])
np.linalg.det(b)

180.0

In [36]:
# проверка в)
c = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
round(np.linalg.det(c), 2)

-0.0

#### 2. Определитель матрицы A равен 4.  
#### Найдите:

$а)  det(A^2);$

$б)  det(A^T);$

$в)  det(2A).$

a) Для двух квадратных матриц одинакового размера:
\begin{equation*}
det(AB) = detA * detB
\\
det(A^2) = 4 ∗ 4 = 16
\end{equation*}

б) Определитель транспонированной матрицы равен определителю
исходной: 
\begin{equation*}
det A^T = det A
\\
det A^T = 4 
\end{equation*}

в) Умножение строки или столбца матрицы на число λ приведёт к
умножению определителя матрицы на то же число. 
\begin{equation*}
det (2 A) = 2^n ∗ 4 = 2^n+^2
\end{equation*}

#### 3. Докажите что это вырожденная матрица:
    -2  7  -3
     4 -14  6
    -3  7   13
Матрица является вырожденной если ее определитель равен нулю.   
Если две строки столбца матрицы линейно зависимы, то определитель
этой матрицы равен нулю.
Так как вторая строка матрицы равна первой строке умноженной ,
на то эти две строки линейно зависимы соответственно определитель матрицы равен нулю что и означает что эта матрица - вырожденная.

= −2 (−14∗13−6∗7) −7 (4∗13+6∗3) −3 (4∗7−(14∗3)) = 448 − 490 + 42 = 0

In [37]:
#Для верности посчитаем определитель матрицы:

c = np.array([[-2, 7, -3], [4, -14, 6],[-3, 7, 13]])
np.linalg.det(c)

0.0

#### 4. Найдите ранг матрицы:
a)

     1  2  3
     1  1  1
     2  3  4
     
Отнимем из второй строки первую:   

     1  2  3
     0 -1 -2
     2  3  4
     
Теперь отнимем из третьей строки первую умноженную на 2  

    1  2  3
    0 -1 -2
    0 -1 -2

Так как вторая и третья строки равны удалим третью строку  

     1  2  3
     0 -1 -2
     
Получилась верхне треугольная матрица таким образом ранг матрицы равен 2.  
     
б)

    0  0  2  1
    0  0  2  2
    0  0  4  3
    2  3  5  6
   
Переместим последную строку наверх на место первой:  

    2  3  5  6
    0  0  2  1
    0  0  2  2
    0  0  4  3
    
Из четвертой строки отнимем вторую умноженную на 2:  

    2  3  5  6
    0  0  2  1
    0  0  2  2
    0  0  0  1

Получилась верхне-треугольная матрица.  

Используем правило:
*Определитель матрицы треугольного вида равен произведению
элементов стоящих на её главной диагонали*.

В нашем случае произведение и определитель равны нулю, так как во второй строке стоит ноль на главной диагонали.
Если убрать вторую строку то ранг матрицы получается равен 3.

In [40]:
#проверка а)
a = np.array([[1, 2, 3], [1, 1, 1],[2, 3, 4]])
np.linalg.matrix_rank(a)

2

In [41]:
#проверка б)
a = np.array([[0, 0, 2, 1], [0, 0, 2, 2], [0, 0, 4, 3], [2, 3, 5, 6]])
np.linalg.matrix_rank(a)

3