<a href="https://colab.research.google.com/github/ViacheslavCRBP/pythonProject/blob/MLB/PyTorch_Less_1_HW_Viacheslav_ipynb%22.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# PyTorch, вводное занятие

## Урок 1.

### Задание

Создайте случайный FloatTensor размера 3x4x5  
Выведите его форму (shape)  
Приведите его к форме 6х10  
Создайте случайный IntTensor размера 10  
Умножьте созданный FloatTensor на созданный IntTensor поэлементно  
Умножьте тензор матрично на себя, чтобы результат был размерности 6x6  Подсказка: .dot может не подойти  
Посчитайте производную функции y = x**3 + z - 75t в точке (1, 0.5, 2)  
Создайте единичный тензор размера 5x6  
Переведите его в формат numpy  

In [1]:
!pip3 install torch torchvision

In [2]:
from IPython import display
import numpy as np
import random
import torch

In [3]:
#Создайте случайный FloatTensor размера 3x4x5

a = torch.FloatTensor([3, 4, 5])
print(a)

tensor([3., 4., 5.])


In [4]:
# Выведите его форму (shape)

print(f"a: {a}\nshape: {a.size()}")

a: tensor([3., 4., 5.])
shape: torch.Size([3])


In [5]:
# Приведите его к форме 6х10

a = torch.FloatTensor([6, 10])
print(a)

tensor([ 6., 10.])


In [6]:
# Создайте случайный IntTensor размера 10

b = torch.IntTensor([10])
print(b)

tensor([10], dtype=torch.int32)


In [7]:
# Умножьте созданный FloatTensor на созданный IntTensor поэлементно

a = torch.Tensor(a)
b = torch.Tensor(b)

tens = torch.mul(a, b)
print("Результат поэлементного умножения FloatTensor на IntTensor: ", tens)


Результат поэлементного умножения FloatTensor на IntTensor:  tensor([ 60., 100.])


In [55]:
# Умножьте тензор матрично на себя, чтобы результат был размерности 6x6

a2 = a.dot(a)

print(a2)

tensor(136.)


In [62]:
# Посчитайте производную функции y = x**3 + z - 75t в точке (1, 0.5, 2)

x=torch.tensor(1.0, requires_grad=True)
z=torch.tensor(0.5, requires_grad=True)
t=2
y = x**3 + z - 75*t
y.backward()
x.grad
z.grad

tensor(1.)

In [25]:
# Создайте единичный тензор размера 5x6

e  = torch.eye(5, 6)
print(e)

tensor([[1., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 1., 0.]])


In [63]:
# Переведите его в формат numpy

e = torch.ones(5)
print(e)

tensor([1., 1., 1., 1., 1.])


In [64]:
# Создайте тензор из единиц размера 5x6

on  = torch.ones(5, 6)
print(on)

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])
